In [1]:
import pandas as pd
import sys

# Print Python version
print("sys.version:", sys.version)

# Print Pandas version
print("pandas version:", pd.__version__)

sys.version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
pandas version: 2.2.0

# Input/Output(Reading and Writing)

In [2]:
# Create a dictionary with the data
data ={
    'Name': ['Praveen', 'Rahul', 'Priyanka'],
    'Age': [32,50,48],
    'City': ['Lucknow', 'Delhi', 'Mumbai']
}
# Create the DataFrame using the dictionary
df = pd.DataFrame(data)
# Printing the DataFrame
df

       Name  Age     City
0   Praveen   32  Lucknow
1     Rahul   50    Delhi
2  Priyanka   48   Mumbai

In [3]:
# Install pkg pyarrow OR fastparquet

In [4]:
# Read the dataset from the Parquet file
df = pd.read_parquet("/kaggle/input/combined-flights-2022/Combined_Flights_2022.parquet")

# Set option to display a maximum of 500 columns
pd.set_option('display.max_columns', 500)

# Check the shape of the DataFrame
print("Shape of the DataFrame:", df.shape)

Shape of the DataFrame: (4078318, 61)

In [5]:
# Display the first few rows of the DataFrame
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0

In [6]:
# Display the last 5 rows of the DataFrame
df.tail()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

In [7]:
# Randomly sample 5 rows from the DataFrame
df.sample(5)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
120803,2022-05-04,United Air Lines Inc.,PDX,DEN,False,False,530,524.0,0.0,-6.0,857.0,0.0,135.0,149.0,153.0,991.0,2022,2,5,4,3,UA,UA,19977,UA,2493,UA,19977,UA,N67827,2493,14057,1405702,34057,"Portland, OR",OR,41,Oregon,92,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,0001-0559,11.0,535.0,850.0,7.0,859,-2.0,0.0,-1.0,0800-0859,4,0
457476,2022-06-14,Endeavor Air Inc.,BOS,MKE,False,False,2025,2039.0,14.0,14.0,2218.0,9.0,123.0,164.0,159.0,860.0,2022,2,6,14,2,DL,DL_CODESHARE,19790,DL,4841,9E,20363,9E,N607LR,4841,10721,1072102,30721,"Boston, MA",MA,25,Massachusetts,13,13342,1334207,33342,"Milwaukee, WI",WI,55,Wisconsin,45,0.0,0.0,2000-2059,29.0,2108.0,2211.0,7.0,2209,9.0,0.0,0.0,2200-2259,4,0
993,2022-06-28,Comair Inc.,PHL,AVL,False,False,1537,1545.0,8.0,8.0,1728.0,7.0,75.0,104.0,103.0,504.0,2022,2,6,28,2,AA,AA_CODESHARE,19805,AA,5443,OH,20397,OH,N535EA,5443,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,10431,1043105,30431,"Asheville, NC",NC,37,North Carolina,36,0.0,0.0,1500-1559,25.0,1610.0,1725.0,3.0,1721,7.0,0.0,0.0,1700-1759,3,0
59517,2022-01-26,Delta Air Lines Inc.,RDU,MSP,False,False,625,612.0,0.0,-13.0,758.0,0.0,149.0,174.0,166.0,980.0,2022,1,1,26,3,DL,DL,19790,DL,2654,DL,19790,DL,N323NB,2654,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,0.0,-1.0,0600-0659,12.0,624.0,753.0,5.0,819,-21.0,0.0,-2.0,0800-0859,4,0
187836,2022-07-22,Delta Air Lines Inc.,ATL,ICT,False,False,1540,1610.0,30.0,30.0,1720.0,28.0,105.0,132.0,130.0,782.0,2022,3,7,22,5,DL,DL,19790,DL,2800,DL,19790,DL,N928AT,2800,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12278,1227805,30928,"Wichita, KS",KS,20,Kansas,62,1.0,2.0,1500-1559,20.0,1630.0,1715.0,5.0,1652,28.0,1.0,1.0,1600-1659,4,0

In [8]:
# Randomly sample 3 rows from the DataFrame with a random state of 42
df.sample(3, random_state=42)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
324021,2022-03-19,SkyWest Airlines Inc.,ASE,DEN,False,False,1831,1826.0,0.0,-5.0,1923.0,0.0,31.0,62.0,57.0,125.0,2022,1,3,19,6,UA,UA_CODESHARE,19977,UA,5745,OO,20304,OO,N794SK,5745,10372,1037205,30372,"Aspen, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1800-1859,19.0,1845.0,1916.0,7.0,1933,-10.0,0.0,-1.0,1900-1959,1,0
34739,2022-02-16,SkyWest Airlines Inc.,TYS,DEN,False,False,1605,1605.0,0.0,0.0,1812.0,35.0,194.0,212.0,247.0,1162.0,2022,1,2,16,3,UA,UA_CODESHARE,19977,UA,5733,OO,20304,OO,N127SY,5733,15412,1541205,35412,"Knoxville, TN",TN,47,Tennessee,54,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1600-1659,9.0,1614.0,1728.0,44.0,1737,35.0,1.0,2.0,1700-1759,5,0
304494,2022-01-18,American Airlines Inc.,LAX,OGG,False,False,1719,1714.0,0.0,-5.0,2052.0,3.0,314.0,330.0,338.0,2486.0,2022,1,1,18,2,AA,AA,19805,AA,205,AA,19805,AA,N400AN,205,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,13830,1383002,33830,"Kahului, HI",HI,15,Hawaii,2,0.0,-1.0,1700-1759,14.0,1728.0,2042.0,10.0,2049,3.0,0.0,0.0,2000-2059,10,0

In [9]:
# Randomly sample 10% of the DataFrame with a random state of 529
df.sample(frac=0.1, random_state=529)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
103009,2022-01-07,Envoy Air,DCA,RDU,False,False,1459,1456.0,0.0,-3.0,1558.0,0.0,43.0,89.0,62.0,227.0,2022,1,1,7,5,AA,AA_CODESHARE,19805,AA,3977,MQ,20398,MQ,N246NN,3977,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1400-1459,13.0,1509.0,1552.0,6.0,1628,-30.0,0.0,-2.0,1600-1659,1,0
505955,2022-06-10,American Airlines Inc.,PHX,DFW,False,False,850,856.0,6.0,6.0,1326.0,3.0,115.0,153.0,150.0,868.0,2022,2,6,10,5,AA,AA,19805,AA,1887,AA,19805,AA,N135NN,1887,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,0.0,0800-0859,22.0,918.0,1313.0,13.0,1323,3.0,0.0,0.0,1300-1359,4,0
162428,2022-07-03,Delta Air Lines Inc.,ATL,MCO,False,False,1459,1458.0,0.0,-1.0,1657.0,23.0,65.0,95.0,119.0,404.0,2022,3,7,3,7,DL,DL,19790,DL,1546,DL,19790,DL,N583NW,1546,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,0.0,-1.0,1400-1459,44.0,1542.0,1647.0,10.0,1634,23.0,1.0,1.0,1600-1659,2,0
328714,2022-02-21,Frontier Airlines Inc.,IAH,MCO,False,False,859,857.0,0.0,-2.0,1200.0,0.0,104.0,142.0,123.0,854.0,2022,1,2,21,1,F9,F9,20436,F9,1250,F9,20436,F9,N230FR,1250,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,0.0,-1.0,0800-0859,9.0,906.0,1150.0,10.0,1221,-21.0,0.0,-2.0,1200-1259,4,0
447780,2022-03-01,Southwest Airlines Co.,DCA,MDW,False,False,2130,2138.0,8.0,8.0,2233.0,0.0,100.0,125.0,115.0,601.0,2022,1,3,1,2,WN,WN,19393,WN,1500,WN,19393,WN,N200WN,1500,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,13232,1323202,30977,"Chicago, IL",IL,17,Illinois,41,0.0,0.0,2100-2159,12.0,2150.0,2230.0,3.0,2235,-2.0,0.0,-1.0,2200-2259,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579190,2022-07-31,Southwest Airlines Co.,BWI,ORF,False,False,1710,1722.0,12.0,12.0,1807.0,2.0,32.0,55.0,45.0,159.0,2022,3,7,31,7,WN,WN,19393,WN,876,WN,19393,WN,N8647A,876,10821,1082106,30852,"Baltimore, MD",MD,24,Maryland,35,13931,1393102,33667,"Norfolk, VA",VA,51,Virginia,38,0.0,0.0,1700-1759,10.0,1732.0,1804.0,3.0,1805,2.0,0.0,0.0,1800-1859,1,0
191950,2022-01-04,Southwest Airlines Co.,AUS,DAL,False,False,1225,1251.0,26.0,26.0,1356.0,31.0,40.0,60.0,65.0,189.0,2022,1,1,4,2,WN,WN,19393,WN,857,WN,19393,WN,N908WN,857,10423,1042302,30423,"Austin, TX",TX,48,Texas,74,11259,1125904,30194,"Dallas, TX",TX,48,Texas,74,1.0,1.0,1200-1259,8.0,1259.0,1339.0,17.0,1325,31.0,1.0,2.0,1300-1359,1,0
185257,2022-02-08,American Airlines Inc.,PHX,LAX,False,False,1956,1950.0,0.0,-6.0,2010.0,0.0,53.0,91.0,80.0,370.0,2022,1,2,8,2,AA,AA,19805,AA,1160,AA,19805,AA,N534UW,1160,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,0.0,-1.0,1900-1959,23.0,2013.0,2006.0,4.0,2027,-17.0,0.0,-2.0,2000-2059,2,0
379494,2022-03-31,United Air Lines Inc.,RSW,SFO,False,False,1901,1858.0,0.0,-3.0,2156.0,0.0,338.0,357.0,358.0,2481.0,2022,1,3,31,4,UA,UA,19977,UA,1280,UA,19977,UA,N17244,1280,14635,1463502,31714,"Fort Myers, FL",FL,12,Florida,33,14771,1477104,32457,"San Francisco, CA",CA,6,California,91,0.0,-1.0,1900-1959,15.0,1913.0,2151.0,5.0,2158,-2.0,0.0,-1.0,2100-2159,10,0
237876,2022-04-01,Capital Cargo International,SBY,PHL,False,False,720,709.0,0.0,-11.0,754.0,0.0,22.0,56.0,45.0,107.0,2022,2,4,1,5,AA,AA_CODESHARE,19805,AA,6161,PT,20427,PT,N646AE,6161,14704,1470405,34704,"Salisbury, MD",MD,24,Maryland,35,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,0.0,-1.0,0700-0759,17.0,726.0,748.0,6.0,816,-22.0,0.0,-2.0,0800-0859,1,0

In [10]:
num_rows_shape = df.shape[0]  # Using df.shape[0]
num_rows_len = len(df)         # Using len(df)

num_rows_shape, num_rows_len

(4078318, 4078318)

# Subsetting A DataFrame

In [11]:
# Select columns 'FlightDate', 'Airline', and 'Origin'
df[['FlightDate', 'Airline', 'Origin']]

       FlightDate                                    Airline Origin
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    IAH
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
...           ...                                        ...    ...
590537 2022-03-31                          Republic Airlines    MSY
590538 2022-03-17                          Republic Airlines    CLT
590539 2022-03-08                          Republic Airlines    ALB
590540 2022-03-25                          Republic Airlines    EWR
590541 2022-03-07                          Republic Airlines    EWR

[4078318 rows x 3 columns]

In [12]:
# Select the first five columns of the DataFrame
df[df.columns[:5]]

,FlightDate,Airline,Origin,Dest,Cancelled
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False
590538,2022-03-17,Republic Airlines,CLT,EWR,True
590539,2022-03-08,Republic Airlines,ALB,ORD,False
590540,2022-03-25,Republic Airlines,EWR,PIT,False
590541,2022-03-07,Republic Airlines,EWR,RDU,False

In [13]:
# Select the last five columns of the DataFrame
df[df.columns[-5:]]

,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,0.0,-2.0,1200-1259,1,0
1,0.0,-1.0,0800-0859,2,0
2,0.0,-1.0,1600-1659,2,0
3,0.0,-2.0,1600-1659,2,0
4,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...
590537,NaN,NaN,2300-2359,5,1
590538,NaN,NaN,1900-1959,3,0
590539,1.0,12.0,1800-1859,3,0
590540,NaN,NaN,2200-2259,2,1
590541,NaN,NaN,1300-1359,2,1

In [14]:
# Filter columns containing 'Time'
[c for c in df.columns if 'Time' in c]

['CRSDepTime',
 'DepTime',
 'ArrTime',
 'AirTime',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'DepTimeBlk',
 'CRSArrTime',
 'ArrTimeBlk']

In [15]:
# Select columns containing 'Time'
df[[c for c in df.columns if 'Time' in c]]

,CRSDepTime,DepTime,ArrTime,AirTime,CRSElapsedTime,ActualElapsedTime,DepTimeBlk,CRSArrTime,ArrTimeBlk
0,1133,1123.0,1228.0,40.0,72.0,65.0,1100-1159,1245,1200-1259
1,732,728.0,848.0,55.0,77.0,80.0,0700-0759,849,0800-0859
2,1529,1514.0,1636.0,47.0,70.0,82.0,1500-1559,1639,1600-1659
3,1435,1430.0,1547.0,57.0,90.0,77.0,1400-1459,1605,1600-1659
4,1135,1135.0,1251.0,49.0,70.0,76.0,1100-1159,1245,1200-1259
...,...,...,...,...,...,...,...,...,...
590537,1949,2014.0,234.0,NaN,185.0,NaN,1900-1959,2354,2300-2359
590538,1733,1817.0,NaN,NaN,129.0,NaN,1700-1759,1942,1900-1959
590539,1700,2318.0,59.0,135.0,158.0,161.0,1700-1759,1838,1800-1859
590540,2129,2322.0,939.0,NaN,86.0,NaN,2100-2159,2255,2200-2259
590541,1154,1148.0,1556.0,NaN,99.0,NaN,1100-1159,1333,1300-1359

In [16]:
# Select columns of integer data type
df.select_dtypes('int')

# Select columns of datetime data type
df.select_dtypes('datetime64')

# Select columns of boolean data type
df.select_dtypes('bool')

# Select columns of object data type
df.select_dtypes('object')

,Airline,Origin,Dest,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,IATA_Code_Marketing_Airline,Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,OriginCityName,OriginState,OriginStateName,DestCityName,DestState,DestStateName,DepTimeBlk,ArrTimeBlk
0,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,UA,UA_CODESHARE,UA,C5,C5,N21144,"Grand Junction, CO",CO,Colorado,"Denver, CO",CO,Colorado,1100-1159,1200-1259
1,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,UA,UA_CODESHARE,UA,C5,C5,N16170,"Harlingen/San Benito, TX",TX,Texas,"Houston, TX",TX,Texas,0700-0759,0800-0859
2,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,UA,UA_CODESHARE,UA,C5,C5,N21144,"Durango, CO",CO,Colorado,"Denver, CO",CO,Colorado,1500-1559,1600-1659
3,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,UA,UA_CODESHARE,UA,C5,C5,N11184,"Houston, TX",TX,Texas,"Gulfport/Biloxi, MS",MS,Mississippi,1400-1459,1600-1659
4,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,UA,UA_CODESHARE,UA,C5,C5,N17146,"Durango, CO",CO,Colorado,"Denver, CO",CO,Colorado,1100-1159,1200-1259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,Republic Airlines,MSY,EWR,UA,UA_CODESHARE,UA,YX,YX,N745YX,"New Orleans, LA",LA,Louisiana,"Newark, NJ",NJ,New Jersey,1900-1959,2300-2359
590538,Republic Airlines,CLT,EWR,UA,UA_CODESHARE,UA,YX,YX,N654RW,"Charlotte, NC",NC,North Carolina,"Newark, NJ",NJ,New Jersey,1700-1759,1900-1959
590539,Republic Airlines,ALB,ORD,UA,UA_CODESHARE,UA,YX,YX,N733YX,"Albany, NY",NY,New York,"Chicago, IL",IL,Illinois,1700-1759,1800-1859
590540,Republic Airlines,EWR,PIT,UA,UA_CODESHARE,UA,YX,YX,N647RW,"Newark, NJ",NJ,New Jersey,"Pittsburgh, PA",PA,Pennsylvania,2100-2159,2200-2259
590541,Republic Airlines,EWR,RDU,UA,UA_CODESHARE,UA,YX,YX,N648RW,"Newark, NJ",NJ,New Jersey,"Raleigh/Durham, NC",NC,North Carolina,1100-1159,1300-1359

In [17]:
# Select the 'Airline' column as Series
df['Airline']

0         Commutair Aka Champlain Enterprises, Inc.
1         Commutair Aka Champlain Enterprises, Inc.
2         Commutair Aka Champlain Enterprises, Inc.
3         Commutair Aka Champlain Enterprises, Inc.
4         Commutair Aka Champlain Enterprises, Inc.
                            ...
590537                            Republic Airlines
590538                            Republic Airlines
590539                            Republic Airlines
590540                            Republic Airlines
590541                            Republic Airlines
Name: Airline, Length: 4078318, dtype: object

In [18]:
# Select the 'Airline' column as a DataFrame
df[['Airline']]

                                          Airline
0       Commutair Aka Champlain Enterprises, Inc.
1       Commutair Aka Champlain Enterprises, Inc.
2       Commutair Aka Champlain Enterprises, Inc.
3       Commutair Aka Champlain Enterprises, Inc.
4       Commutair Aka Champlain Enterprises, Inc.
...                                           ...
590537                          Republic Airlines
590538                          Republic Airlines
590539                          Republic Airlines
590540                          Republic Airlines
590541                          Republic Airlines

[4078318 rows x 1 columns]

# Filtering Rows

`df.loc[]` and `df.iloc[]`

# iloc

In [19]:
# Access a specific value at row 1, column 6
df.iloc[1, 6]

732

In [20]:
# Access the first 3 rows and the first 5 columns
df.iloc[:3, :5]

  FlightDate                                    Airline Origin Dest  Cancelled
0 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT  DEN      False
1 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL  IAH      False
2 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False

In [21]:
# Access the values at row 5
df.iloc[5]

FlightDate                                  2022-04-04 00:00:00
Airline               Commutair Aka Champlain Enterprises, Inc.
Origin                                                      DEN
Dest                                                        TUL
Cancelled                                                 False
                                        ...
ArrDel15                                                    0.0
ArrivalDelayGroups                                         -1.0
ArrTimeBlk                                            1200-1259
DistanceGroup                                                 3
DivAirportLandings                                            0
Name: 5, Length: 61, dtype: object

In [22]:
# Access the values at row 5 as a DataFrame
df.iloc[[5]]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
5,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DEN,TUL,False,False,955,952.0,0.0,-3.0,1238.0,0.0,77.0,105.0,106.0,541.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4294,C5,20445,C5,N11191,4294,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,15370,1537002,34653,"Tulsa, OK",OK,40,Oklahoma,73,0.0,-1.0,0900-0959,25.0,1017.0,1234.0,4.0,1240,-2.0,0.0,-1.0,1200-1259,3,0

In [23]:
# Access the values in the second column
df.iloc[:, 1]

0         Commutair Aka Champlain Enterprises, Inc.
1         Commutair Aka Champlain Enterprises, Inc.
2         Commutair Aka Champlain Enterprises, Inc.
3         Commutair Aka Champlain Enterprises, Inc.
4         Commutair Aka Champlain Enterprises, Inc.
                            ...
590537                            Republic Airlines
590538                            Republic Airlines
590539                            Republic Airlines
590540                            Republic Airlines
590541                            Republic Airlines
Name: Airline, Length: 4078318, dtype: object

In [24]:
# Access the values of the first 3 rows and the first 3 columns
df.iloc[:3, [0, 1, 2]]

  FlightDate                                    Airline Origin
0 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT
1 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL
2 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO

In [25]:
# Access the values of the first 3 rows and the first 5 columns
df.iloc[:3, 0:5]

  FlightDate                                    Airline Origin Dest  Cancelled
0 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT  DEN      False
1 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL  IAH      False
2 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False

# loc

In [26]:
# Select specific columns 'Airline', 'Origin', 'Dest', and 'Cancelled'
df.loc[:, ['Airline', 'Origin', 'Dest', 'Cancelled']]

                                          Airline Origin Dest  Cancelled
0       Commutair Aka Champlain Enterprises, Inc.    GJT  DEN      False
1       Commutair Aka Champlain Enterprises, Inc.    HRL  IAH      False
2       Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False
3       Commutair Aka Champlain Enterprises, Inc.    IAH  GPT      False
4       Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False
...                                           ...    ...  ...        ...
590537                          Republic Airlines    MSY  EWR      False
590538                          Republic Airlines    CLT  EWR       True
590539                          Republic Airlines    ALB  ORD      False
590540                          Republic Airlines    EWR  PIT      False
590541                          Republic Airlines    EWR  RDU      False

[4078318 rows x 4 columns]

In [27]:
# Select specific columns 'Airline', 'Origin', 'Dest', and 'Cancelled' for rows up to index 3
df.iloc[:4, df.columns.isin(['Airline', 'Origin', 'Dest', 'Cancelled'])]

                                     Airline Origin Dest  Cancelled
0  Commutair Aka Champlain Enterprises, Inc.    GJT  DEN      False
1  Commutair Aka Champlain Enterprises, Inc.    HRL  IAH      False
2  Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False
3  Commutair Aka Champlain Enterprises, Inc.    IAH  GPT      False

In [28]:
# Select rows where the 'Airline' is 'Spirit Air Lines'
df.loc[df['Airline'] == 'Spirit Air Lines']

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
407040,2022-04-01,Spirit Air Lines,FLL,ORD,True,False,2025,NaN,NaN,NaN,NaN,NaN,NaN,193.0,NaN,1182.0,2022,2,4,1,5,NK,NK,20416,NK,1,NK,20416,NK,N669NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2238,NaN,NaN,NaN,2200-2259,5,0
407041,2022-04-02,Spirit Air Lines,FLL,ORD,True,False,2147,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,1182.0,2022,2,4,2,6,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2100-2159,NaN,NaN,NaN,NaN,2359,NaN,NaN,NaN,2300-2359,5,0
407042,2022-04-03,Spirit Air Lines,FLL,ORD,False,False,2147,211.0,264.0,264.0,421.0,262.0,163.0,192.0,190.0,1182.0,2022,2,4,3,7,NK,NK,20416,NK,1,NK,20416,NK,N661NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,2100-2159,18.0,229.0,412.0,9.0,2359,262.0,1.0,12.0,2300-2359,5,0
407043,2022-04-04,Spirit Air Lines,FLL,ORD,False,False,2147,2227.0,40.0,40.0,39.0,40.0,157.0,192.0,192.0,1182.0,2022,2,4,4,1,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,2.0,2100-2159,25.0,2252.0,29.0,10.0,2359,40.0,1.0,2.0,2300-2359,5,0
407044,2022-04-05,Spirit Air Lines,FLL,ORD,False,False,2200,2252.0,52.0,52.0,58.0,46.0,164.0,192.0,186.0,1182.0,2022,2,4,5,2,NK,NK,20416,NK,1,NK,20416,NK,N681NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,3.0,2200-2259,13.0,2305.0,49.0,9.0,12,46.0,1.0,3.0,0001-0559,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142478,2022-03-27,Spirit Air Lines,EWR,LAS,False,False,1700,1705.0,5.0,5.0,2019.0,58.0,297.0,321.0,374.0,2227.0,2022,1,3,27,7,NK,NK,20416,NK,993,NK,20416,NK,N693NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,69.0,1814.0,2011.0,8.0,1921,58.0,1.0,3.0,1900-1959,9,0
142479,2022-03-28,Spirit Air Lines,EWR,LAS,False,False,1700,1802.0,62.0,62.0,2043.0,82.0,312.0,321.0,341.0,2227.0,2022,1,3,28,1,NK,NK,20416,NK,993,NK,20416,NK,N641NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,24.0,1826.0,2038.0,5.0,1921,82.0,1.0,5.0,1900-1959,9,0
142480,2022-03-29,Spirit Air Lines,EWR,LAS,False,False,1700,1654.0,0.0,-6.0,1912.0,0.0,300.0,321.0,318.0,2227.0,2022,1,3,29,2,NK,NK,20416,NK,993,NK,20416,NK,N623NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,1700-1759,11.0,1705.0,1905.0,7.0,1921,-9.0,0.0,-1.0,1900-1959,9,0
142481,2022-03-30,Spirit Air Lines,EWR,LAS,False,False,1700,1709.0,9.0,9.0,2004.0,43.0,296.0,321.0,355.0,2227.0,2022,1,3,30,3,NK,NK,20416,NK,993,NK,20416,NK,N645NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,52.0,1801.0,1957.0,7.0,1921,43.0,1.0,2.0,1900-1959,9,0
142482,2022-03-31,Spirit Air Lines,EWR,LAS,True,False,1700,1804.0,64.0,64.0,NaN,NaN,NaN,321.0,NaN,2227.0,2022,1,3,31,4,NK,NK,20416,NK,993,NK,20416,NK,N650NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,NaN,NaN,NaN,NaN,1921,NaN,NaN,NaN,1900-1959,9,0

In [29]:
# Select rows where the 'Airline' is 'Spirit Air Lines' and the 'FlightDate' is '2022-04-01'
df.loc[(df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-04-01')]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
407040,2022-04-01,Spirit Air Lines,FLL,ORD,True,False,2025,NaN,NaN,NaN,NaN,NaN,NaN,193.0,NaN,1182.0,2022,2,4,1,5,NK,NK,20416,NK,1,NK,20416,NK,N669NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2238,NaN,NaN,NaN,2200-2259,5,0
407070,2022-04-01,Spirit Air Lines,ORD,FLL,False,False,515,514.0,0.0,-1.0,908.0,0.0,152.0,180.0,174.0,1182.0,2022,2,4,1,5,NK,NK,20416,NK,2,NK,20416,NK,N658NK,2,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,-1.0,0001-0559,12.0,526.0,858.0,10.0,915,-7.0,0.0,-1.0,0900-0959,5,0
407100,2022-04-01,Spirit Air Lines,ORD,FLL,False,False,755,750.0,0.0,-5.0,1144.0,0.0,156.0,182.0,174.0,1182.0,2022,2,4,1,5,NK,NK,20416,NK,3,NK,20416,NK,N669NK,3,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,-1.0,0700-0759,11.0,801.0,1137.0,7.0,1157,-13.0,0.0,-1.0,1100-1159,5,0
407130,2022-04-01,Spirit Air Lines,FLL,ORD,False,False,1637,1917.0,160.0,160.0,2125.0,155.0,159.0,193.0,188.0,1182.0,2022,2,4,1,5,NK,NK,20416,NK,6,NK,20416,NK,N658NK,6,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,10.0,1600-1659,22.0,1939.0,2118.0,7.0,1850,155.0,1.0,10.0,1800-1859,5,0
407183,2022-04-01,Spirit Air Lines,CLT,LAS,False,False,1715,1813.0,58.0,58.0,1954.0,57.0,263.0,282.0,281.0,1916.0,2022,2,4,1,5,NK,NK,20416,NK,51,NK,20416,NK,N903NK,51,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,3.0,1700-1759,14.0,1827.0,1950.0,4.0,1857,57.0,1.0,3.0,1800-1859,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425552,2022-04-01,Spirit Air Lines,CLT,FLL,False,False,850,1305.0,255.0,255.0,1609.0,329.0,130.0,110.0,184.0,632.0,2022,2,4,1,5,NK,NK,20416,NK,980,NK,20416,NK,N944NK,980,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,1.0,12.0,0800-0859,43.0,1348.0,1558.0,11.0,1040,329.0,1.0,12.0,1000-1059,3,0
425582,2022-04-01,Spirit Air Lines,FLL,CLT,False,False,1420,1438.0,18.0,18.0,1725.0,64.0,101.0,121.0,167.0,632.0,2022,2,4,1,5,NK,NK,20416,NK,981,NK,20416,NK,N903NK,981,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,1.0,1.0,1400-1459,60.0,1538.0,1719.0,6.0,1621,64.0,1.0,4.0,1600-1659,3,0
425612,2022-04-01,Spirit Air Lines,DTW,MSY,False,False,1627,1630.0,3.0,3.0,1759.0,2.0,135.0,150.0,149.0,926.0,2022,2,4,1,5,NK,NK,20416,NK,985,NK,20416,NK,N502NK,985,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,0.0,0.0,1600-1659,8.0,1638.0,1753.0,6.0,1757,2.0,0.0,0.0,1700-1759,4,0
425633,2022-04-01,Spirit Air Lines,MSY,ORD,False,False,917,909.0,0.0,-8.0,1134.0,0.0,119.0,150.0,145.0,836.0,2022,2,4,1,5,NK,NK,20416,NK,992,NK,20416,NK,N651NK,992,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0900-0959,10.0,919.0,1118.0,16.0,1147,-13.0,0.0,-1.0,1100-1159,4,0
425663,2022-04-01,Spirit Air Lines,EWR,LAS,False,False,1700,1706.0,6.0,6.0,1919.0,0.0,292.0,321.0,313.0,2227.0,2022,2,4,1,5,NK,NK,20416,NK,993,NK,20416,NK,N650NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,16.0,1722.0,1914.0,5.0,1921,-2.0,0.0,-1.0,1900-1959,9,0

In [30]:
# Select rows where the 'Airline' is not 'Spirit Air Lines' and the 'FlightDate' is '2022-04-01'
df.loc[~((df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-04-01'))]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

In [31]:
# Alternative syntax for the previous operation
df.loc[~((df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-04-01'))]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

# Filtering Using Query

In [32]:
# Query the DataFrame for flights with departure time greater than 1130 and origin at 'DRO'
df.query('(DepTime > 1130) and (Origin == "DRO")')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
531,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1524.0,0.0,-5.0,1633.0,0.0,50.0,70.0,69.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N11191,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,9.0,1533.0,1623.0,10.0,1639,-6.0,0.0,-1.0,1600-1659,2,0
533,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1134.0,0.0,-1.0,1247.0,2.0,43.0,70.0,73.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N31131,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,19.0,1153.0,1236.0,11.0,1245,2.0,0.0,0.0,1200-1259,2,0
1003,2022-04-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1644.0,75.0,75.0,1757.0,78.0,46.0,70.0,73.0,251.0,2022,2,4,2,6,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N16151,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,5.0,1500-1559,15.0,1659.0,1745.0,12.0,1639,78.0,1.0,5.0,1600-1659,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445339,2022-03-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1521.0,0.0,-9.0,1645.0,5.0,50.0,70.0,84.0,251.0,2022,1,3,3,4,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N12163,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,27.0,1548.0,1638.0,7.0,1640,5.0,0.0,0.0,1600-1659,2,0
445977,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1531.0,1.0,1.0,1651.0,11.0,50.0,70.0,80.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N33182,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1500-1559,19.0,1550.0,1640.0,11.0,1640,11.0,0.0,0.0,1600-1659,2,0
445986,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1142.0,7.0,7.0,1245.0,0.0,46.0,70.0,63.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N33182,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,11.0,1153.0,1239.0,6.0,1245,0.0,0.0,0.0,1200-1259,2,0
446617,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1741.0,131.0,131.0,1909.0,149.0,52.0,70.0,88.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N16178,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,8.0,1500-1559,25.0,1806.0,1858.0,11.0,1640,149.0,1.0,9.0,1600-1659,2,0
446626,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1419.0,164.0,164.0,1523.0,158.0,46.0,70.0,64.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N14174,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,10.0,1100-1159,11.0,1430.0,1516.0,7.0,1245,158.0,1.0,10.0,1200-1259,2,0

In [33]:
# Define variables for conditions
min_time = 1130
origin = 'DRO'

# Query the DataFrame using variables for conditions
df.query('(DepTime > @min_time) and (Origin == @origin)')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
531,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1524.0,0.0,-5.0,1633.0,0.0,50.0,70.0,69.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N11191,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,9.0,1533.0,1623.0,10.0,1639,-6.0,0.0,-1.0,1600-1659,2,0
533,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1134.0,0.0,-1.0,1247.0,2.0,43.0,70.0,73.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N31131,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,19.0,1153.0,1236.0,11.0,1245,2.0,0.0,0.0,1200-1259,2,0
1003,2022-04-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1644.0,75.0,75.0,1757.0,78.0,46.0,70.0,73.0,251.0,2022,2,4,2,6,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N16151,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,5.0,1500-1559,15.0,1659.0,1745.0,12.0,1639,78.0,1.0,5.0,1600-1659,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445339,2022-03-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1521.0,0.0,-9.0,1645.0,5.0,50.0,70.0,84.0,251.0,2022,1,3,3,4,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N12163,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,27.0,1548.0,1638.0,7.0,1640,5.0,0.0,0.0,1600-1659,2,0
445977,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1531.0,1.0,1.0,1651.0,11.0,50.0,70.0,80.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N33182,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1500-1559,19.0,1550.0,1640.0,11.0,1640,11.0,0.0,0.0,1600-1659,2,0
445986,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1142.0,7.0,7.0,1245.0,0.0,46.0,70.0,63.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N33182,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,11.0,1153.0,1239.0,6.0,1245,0.0,0.0,0.0,1200-1259,2,0
446617,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1741.0,131.0,131.0,1909.0,149.0,52.0,70.0,88.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N16178,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,8.0,1500-1559,25.0,1806.0,1858.0,11.0,1640,149.0,1.0,9.0,1600-1659,2,0
446626,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1419.0,164.0,164.0,1523.0,158.0,46.0,70.0,64.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N14174,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,10.0,1100-1159,11.0,1430.0,1516.0,7.0,1245,158.0,1.0,10.0,1200-1259,2,0

# Summarizing Data

In [34]:
# Calculate the sum of departure times
df['DepTime'].sum()

# Calculate the mean of departure times
df['DepTime'].mean()

# Count the number of non-null departure times
df['DepTime'].count()

# Calculate the median of departure times
df['DepTime'].median()

# Calculate the mode of departure times
df['DepTime'].mode()

# Calculate the standard deviation of departure times
df['DepTime'].std()

# Find the minimum departure time
df['DepTime'].min()

# Find the maximum departure time
df['DepTime'].max()

# Calculate the variance of departure times
df['DepTime'].var()

# Calculate the 50th percentile (median) of departure times
df['DepTime'].quantile(0.5)

# Calculate the 25th, 50th, and 75th percentiles of departure times
df['DepTime'].quantile([0.25, 0.5, 0.75])

0.25     917.0
0.50    1325.0
0.75    1744.0
Name: DepTime, dtype: float64

In [35]:
# Calculate the mean of 'DepTime', 'DepDelay', 'ArrTime', and 'ArrDelay'
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].mean()

DepTime     1334.373931
DepDelay      13.090487
ArrTime     1457.886018
ArrDelay       7.528486
dtype: float64

In [36]:
# Calculate the mean, minimum, and maximum of 'DepTime', 'DepDelay', 'ArrTime', and 'ArrDelay'
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(['mean', 'min', 'max'])

          DepTime     DepDelay      ArrTime     ArrDelay
mean  1334.373931    13.090487  1457.886018     7.528486
min      1.000000   -78.000000     1.000000  -100.000000
max   2400.000000  7223.000000  2400.000000  7232.000000

In [37]:
# Calculate the minimum and maximum of 'DepTime' and 'ArrTime', and the mean of 'DepDelay'
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg({
    "DepTime": ['min', 'max'],
    "DepDelay": ['mean'],
    "ArrTime": ['min', 'max']
})

      DepTime   DepDelay  ArrTime
min       1.0        NaN      1.0
max    2400.0        NaN   2400.0
mean      NaN  13.090487      NaN

# Summarizing Categorical Variables

In [38]:
# Get the unique values in the 'Airline' column
df['Airline'].unique()

array(['Commutair Aka Champlain Enterprises, Inc.',
       'GoJet Airlines, LLC d/b/a United Express',
       'Air Wisconsin Airlines Corp', 'Mesa Airlines Inc.',
       'Southwest Airlines Co.', 'Republic Airlines', 'Endeavor Air Inc.',
       'American Airlines Inc.', 'Capital Cargo International',
       'SkyWest Airlines Inc.', 'Alaska Airlines Inc.', 'JetBlue Airways',
       'Delta Air Lines Inc.', 'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Spirit Air Lines',
       'Comair Inc.', 'Horizon Air', 'United Air Lines Inc.'],
      dtype=object)

In [39]:
# Count the number of unique values in the 'Airline' column
df['Airline'].nunique()

21

In [40]:
# Count the frequency of each unique value in the 'Airline' column
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       731925
Delta Air Lines Inc.                         512114
American Airlines Inc.                       495953
SkyWest Airlines Inc.                        440807
United Air Lines Inc.                        352009
Republic Airlines                            197881
JetBlue Airways                              156793
Envoy Air                                    150758
Endeavor Air Inc.                            142624
Comair Inc.                                  135884
Alaska Airlines Inc.                         129510
Spirit Air Lines                             129208
Frontier Airlines Inc.                        86557
Allegiant Air                                 73504
Mesa Airlines Inc.                            71972
Horizon Air                                   56320
Capital Cargo International                   52827
Commutair Aka Champlain Enterprises, Inc.     44367
Hawaiian Airlines Inc.                        42212
Air Wisconsin Airlines Corp                   40300
GoJet Airlines, LLC d/b/a United Express      34793
Name: count, dtype: int64

In [41]:
# Count the frequency of each unique value in the 'Airline' column
df['Airline'].value_counts(normalize=True)

Airline
Southwest Airlines Co.                       0.179467
Delta Air Lines Inc.                         0.125570
American Airlines Inc.                       0.121607
SkyWest Airlines Inc.                        0.108085
United Air Lines Inc.                        0.086312
Republic Airlines                            0.048520
JetBlue Airways                              0.038446
Envoy Air                                    0.036966
Endeavor Air Inc.                            0.034971
Comair Inc.                                  0.033319
Alaska Airlines Inc.                         0.031756
Spirit Air Lines                             0.031682
Frontier Airlines Inc.                       0.021224
Allegiant Air                                0.018023
Mesa Airlines Inc.                           0.017647
Horizon Air                                  0.013810
Capital Cargo International                  0.012953
Commutair Aka Champlain Enterprises, Inc.    0.010879
Hawaiian Airlines Inc.                       0.010350
Air Wisconsin Airlines Corp                  0.009882
GoJet Airlines, LLC d/b/a United Express     0.008531
Name: proportion, dtype: float64

In [42]:
# Count the frequency of each unique value in the 'Airline' column and display as percentages
df['Airline'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%'

Airline
Southwest Airlines Co.                       17.95%
Delta Air Lines Inc.                         12.56%
American Airlines Inc.                       12.16%
SkyWest Airlines Inc.                        10.81%
United Air Lines Inc.                         8.63%
Republic Airlines                             4.85%
JetBlue Airways                               3.84%
Envoy Air                                      3.7%
Endeavor Air Inc.                              3.5%
Comair Inc.                                   3.33%
Alaska Airlines Inc.                          3.18%
Spirit Air Lines                              3.17%
Frontier Airlines Inc.                        2.12%
Allegiant Air                                  1.8%
Mesa Airlines Inc.                            1.76%
Horizon Air                                   1.38%
Capital Cargo International                    1.3%
Commutair Aka Champlain Enterprises, Inc.     1.09%
Hawaiian Airlines Inc.                        1.04%
Air Wisconsin Airlines Corp                   0.99%
GoJet Airlines, LLC d/b/a United Express      0.85%
Name: proportion, dtype: object

In [43]:
# Count the frequency of each unique combination of 'Airline' and 'Origin' columns
df[['Airline', 'Origin']].value_counts().reset_index()

                                        Airline Origin   count
0                          Delta Air Lines Inc.    ATL  120919
1                        American Airlines Inc.    DFW   81239
2                        American Airlines Inc.    CLT   57914
3                         United Air Lines Inc.    DEN   46489
4                        Southwest Airlines Co.    DEN   45398
...                                         ...    ...     ...
2189                     Frontier Airlines Inc.    ICT       1
2190                         Mesa Airlines Inc.    MDT       1
2191                Air Wisconsin Airlines Corp    FWA       1
2192  Commutair Aka Champlain Enterprises, Inc.    DSM       1
2193   GoJet Airlines, LLC d/b/a United Express    MKE       1

[2194 rows x 3 columns]

# Advanced Column Methods

In [44]:
df.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [45]:
# Create a DataFrame
dfnew = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
                   'Score': [85, 70, 92, 80, 78]})

# Rank the DataFrame based on the 'Score' column
dfnew['Rank'] = dfnew['Score'].rank(ascending=False)  # By default, ascending=True ranks from lowest to highest
print(dfnew)

      Name  Score  Rank
0    Alice     85   2.0
1      Bob     70   5.0
2  Charlie     92   1.0
3    David     80   3.0
4    Emily     78   4.0

In [46]:
# Compute rank of each element in the 'CRSDepTime' column
df[['CRSDepTime']].rank()

        CRSDepTime
0        1607887.5
1         595750.5
2        2549367.0
3        2344374.5
4        1615667.5
...            ...
590537   3576231.5
590538   3053676.0
590539   2916510.0
590540   3877928.5
590541   1678988.0

[4078318 rows x 1 columns]

In [47]:
# Compute rank of each element in the 'CRSDepTime' column using dense method
df[['CRSDepTime']].rank(method='dense')

        CRSDepTime
0            574.0
1            333.0
2            810.0
3            756.0
4            576.0
...            ...
590537      1070.0
590538       934.0
590539       901.0
590540      1170.0
590541       595.0

[4078318 rows x 1 columns]

In [48]:
# Compute rank of each element in the 'CRSDepTime' column using first method
df[['CRSDepTime']].rank(method='first')

        CRSDepTime
0        1607043.0
1         594869.0
2        2547637.0
3        2338954.0
4        1610842.0
...            ...
590537   3576966.0
590538   3054522.0
590539   2925978.0
590540   3879124.0
590541   1679890.0

[4078318 rows x 1 columns]

In [49]:
# Shift the 'CRSDepTime' column by 1 position
df[['CRSDepTime']].shift(1)

        CRSDepTime
0              NaN
1           1133.0
2            732.0
3           1529.0
4           1435.0
...            ...
590537      2035.0
590538      1949.0
590539      1733.0
590540      1700.0
590541      2129.0

[4078318 rows x 1 columns]

In [50]:
# Shift the 'CRSDepTime' column by 3 positions
df[['CRSDepTime']].shift(3)

        CRSDepTime
0              NaN
1              NaN
2              NaN
3           1133.0
4            732.0
...            ...
590537      1750.0
590538      1829.0
590539      2035.0
590540      1949.0
590541      1733.0

[4078318 rows x 1 columns]

In [51]:
# Shift the 'CRSDepTime' column by 3 positions with fill value 0
df[['CRSDepTime']].shift(3, fill_value=0)

        CRSDepTime
0                0
1                0
2                0
3             1133
4              732
...            ...
590537        1750
590538        1829
590539        2035
590540        1949
590541        1733

[4078318 rows x 1 columns]

In [52]:
# Compute cumulative sum of the 'CRSDepTime' column
df[['CRSDepTime']].cumsum()

        CRSDepTime
0             1133
1             1865
2             3394
3             4829
4             5964
...            ...
590537  5422470512
590538  5422472245
590539  5422473945
590540  5422476074
590541  5422477228

[4078318 rows x 1 columns]

In [53]:
# Compute cumulative maximum of the 'CRSDepTime' column
df[['CRSDepTime']].cummax()

        CRSDepTime
0             1133
1             1133
2             1529
3             1529
4             1529
...            ...
590537        2359
590538        2359
590539        2359
590540        2359
590541        2359

[4078318 rows x 1 columns]

In [54]:
# Compute cumulative minimum of the 'CRSDepTime' column
df[['CRSDepTime']].cummin()

        CRSDepTime
0             1133
1              732
2              732
3              732
4              732
...            ...
590537           1
590538           1
590539           1
590540           1
590541           1

[4078318 rows x 1 columns]

In [55]:
# Compute rolling mean of the 'CRSDepTime' column with window size 5
df[['CRSDepTime']].rolling(window=5).mean()

        CRSDepTime
0              NaN
1              NaN
2              NaN
3              NaN
4           1192.8
...            ...
590537      1796.2
590538      1859.2
590539      1849.2
590540      1909.2
590541      1733.0

[4078318 rows x 1 columns]

In [56]:
# Clip values in the 'CRSDepTime' column to be within a specific range
df[['CRSDepTime']].clip()

        CRSDepTime
0             1133
1              732
2             1529
3             1435
4             1135
...            ...
590537        1949
590538        1733
590539        1700
590540        2129
590541        1154

[4078318 rows x 1 columns]

In [57]:
# Clip values in the 'CRSDepTime' column to be within the range [1000, 2000]
df[['CRSDepTime']].clip(1000, 2000)

        CRSDepTime
0             1133
1             1000
2             1529
3             1435
4             1135
...            ...
590537        1949
590538        1733
590539        1700
590540        2000
590541        1154

[4078318 rows x 1 columns]

# Groupby Methods

In [58]:
# Compute mean departure delay for each airline
df.groupby('Airline')[['DepDelay']].mean()

                                            DepDelay
Airline
Air Wisconsin Airlines Corp                 7.913244
Alaska Airlines Inc.                        5.925950
Allegiant Air                              19.061569
American Airlines Inc.                     14.876556
Capital Cargo International                 6.044430
Comair Inc.                                12.693968
Commutair Aka Champlain Enterprises, Inc.  12.093640
Delta Air Lines Inc.                       11.398599
Endeavor Air Inc.                           9.696390
Envoy Air                                   6.883448
Frontier Airlines Inc.                     20.052761
GoJet Airlines, LLC d/b/a United Express   16.741980
Hawaiian Airlines Inc.                      6.612163
Horizon Air                                 5.892804
JetBlue Airways                            26.009890
Mesa Airlines Inc.                         15.714753
Republic Airlines                          10.811487
SkyWest Airlines Inc.                      11.247036
Southwest Airlines Co.                     14.563121
Spirit Air Lines                           15.621816
United Air Lines Inc.                      13.730542

In [59]:
# Compute mean, minimum, and maximum departure delay for each airline
df.groupby('Airline')[['DepDelay']].agg(['mean', 'min', 'max'])

                                            DepDelay
                                                mean   min     max
Airline
Air Wisconsin Airlines Corp                 7.913244 -30.0  1355.0
Alaska Airlines Inc.                        5.925950 -63.0   915.0
Allegiant Air                              19.061569 -37.0  1917.0
American Airlines Inc.                     14.876556 -35.0  2994.0
Capital Cargo International                 6.044430 -34.0  1512.0
Comair Inc.                                12.693968 -49.0  1607.0
Commutair Aka Champlain Enterprises, Inc.  12.093640 -27.0  1464.0
Delta Air Lines Inc.                       11.398599 -38.0  1287.0
Endeavor Air Inc.                           9.696390 -34.0  1973.0
Envoy Air                                   6.883448 -29.0  5327.0
Frontier Airlines Inc.                     20.052761 -40.0  1288.0
GoJet Airlines, LLC d/b/a United Express   16.741980 -43.0  1220.0
Hawaiian Airlines Inc.                      6.612163 -32.0  1847.0
Horizon Air                                 5.892804 -38.0   803.0
JetBlue Airways                            26.009890 -56.0  2052.0
Mesa Airlines Inc.                         15.714753 -35.0  1837.0
Republic Airlines                          10.811487 -55.0  7223.0
SkyWest Airlines Inc.                      11.247036 -55.0  2366.0
Southwest Airlines Co.                     14.563121 -52.0   747.0
Spirit Air Lines                           15.621816 -39.0  1436.0
United Air Lines Inc.                      13.730542 -78.0  1520.0

In [60]:
# Compute mean, minimum, and maximum departure delay and arrival delay for each airline
df_agg = df.groupby('Airline')[['DepDelay', 'ArrDelay']].agg(['mean', 'min', 'max'])

In [61]:
# Flatten the multi-level column index
df_agg.columns = df_agg.columns.to_flat_index()

In [62]:
# Rename the columns with a joined string of original column names
df_agg.columns = ['_'.join(c) for c in df_agg.columns]

# New Columns

In [63]:
# Create a new column 'DepTime_2' by dividing 'DepTime' by 60
df['DepTime_2'] = df['DepTime'] / 60

In [64]:
# Use the 'assign' method to create a new column 'DepTime_New' by dividing 'DepTime' by 2
df = df.assign(DepTime_New = df['DepTime'] / 2)

# Sorting Data

In [65]:
# Sort the DataFrame by 'ArrDelay' column in ascending order
df.sort_values('ArrDelay')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime_2,DepTime_New
412626,2022-01-20,JetBlue Airways,STT,EWR,False,False,1242,1223.0,0.0,-19.0,1542.0,0.0,236.0,340.0,259.0,1634.0,2022,1,1,20,4,B6,B6,20409,B6,886,B6,20409,B6,N775JB,886,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-2.0,1200-1259,15.0,1238.0,1534.0,8.0,1722,-100.0,0.0,-2.0,1700-1759,7,0,20.383333,611.5
268256,2022-03-30,JetBlue Airways,STT,JFK,False,False,1641,1626.0,0.0,-15.0,2024.0,0.0,222.0,318.0,238.0,1623.0,2022,1,3,30,3,B6,B6,20409,B6,830,B6,20409,B6,N2039J,830,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,12478,1247805,31703,"New York, NY",NY,36,New York,22,0.0,-1.0,1600-1659,10.0,1636.0,2018.0,6.0,2159,-95.0,0.0,-2.0,2100-2159,7,0,27.100000,813.0
398369,2022-01-22,JetBlue Airways,STT,JFK,False,False,1812,1810.0,0.0,-2.0,2102.0,0.0,210.0,321.0,232.0,1623.0,2022,1,1,22,6,B6,B6,20409,B6,830,B6,20409,B6,N2105J,830,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,12478,1247805,31703,"New York, NY",NY,36,New York,22,0.0,-1.0,1800-1859,10.0,1820.0,2050.0,12.0,2233,-91.0,0.0,-2.0,2200-2259,7,0,30.166667,905.0
284876,2022-04-12,Delta Air Lines Inc.,SAN,ATL,False,False,1300,1259.0,0.0,-1.0,1959.0,0.0,209.0,325.0,240.0,1892.0,2022,2,4,12,2,DL,DL,19790,DL,350,DL,19790,DL,N723TW,350,14679,1467903,33570,"San Diego, CA",CA,6,California,91,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1300-1359,25.0,1324.0,1953.0,6.0,2125,-86.0,0.0,-2.0,2100-2159,8,0,20.983333,629.5
583512,2022-05-12,Republic Airlines,LGA,IAH,False,False,1315,1302.0,0.0,-13.0,1520.0,0.0,168.0,266.0,198.0,1416.0,2022,2,5,12,4,AA,AA_CODESHARE,19805,AA,4816,YX,20452,YX,N420YX,4816,12953,1295304,31703,"New York, NY",NY,36,New York,22,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,1300-1359,21.0,1323.0,1511.0,9.0,1641,-81.0,0.0,-2.0,1600-1659,6,0,21.700000,651.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,2022-03-31,Republic Airlines,EWR,PIT,True,False,1829,2033.0,124.0,124.0,NaN,NaN,NaN,97.0,NaN,319.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3687,YX,20452,YX,N651RW,3687,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,8.0,1800-1859,NaN,NaN,NaN,NaN,2006,NaN,NaN,NaN,2000-2059,2,0,33.883333,1016.5
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1,33.566667,1007.0
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0,30.283333,908.5
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1,38.700000,1161.0
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1,19.133333,574.0

In [66]:
# Sort the selected columns 'FlightDate', 'Airline', 'ArrDelay' by 'ArrDelay' column in ascending order
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay')

       FlightDate               Airline  ArrDelay
412626 2022-01-20       JetBlue Airways    -100.0
268256 2022-03-30       JetBlue Airways     -95.0
398369 2022-01-22       JetBlue Airways     -91.0
284876 2022-04-12  Delta Air Lines Inc.     -86.0
583512 2022-05-12     Republic Airlines     -81.0
...           ...                   ...       ...
590535 2022-03-31     Republic Airlines       NaN
590537 2022-03-31     Republic Airlines       NaN
590538 2022-03-17     Republic Airlines       NaN
590540 2022-03-25     Republic Airlines       NaN
590541 2022-03-07     Republic Airlines       NaN

[4078318 rows x 3 columns]

In [67]:
# Sort the selected columns 'FlightDate', 'Airline', 'ArrDelay' by 'ArrDelay' column in descending order
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False)

       FlightDate                 Airline  ArrDelay
249863 2022-05-23       Republic Airlines    7232.0
553561 2022-06-18               Envoy Air    5324.0
249859 2022-05-16       Republic Airlines    4318.0
485902 2022-06-05  American Airlines Inc.    2977.0
190829 2022-03-26  American Airlines Inc.    2934.0
...           ...                     ...       ...
590535 2022-03-31       Republic Airlines       NaN
590537 2022-03-31       Republic Airlines       NaN
590538 2022-03-17       Republic Airlines       NaN
590540 2022-03-25       Republic Airlines       NaN
590541 2022-03-07       Republic Airlines       NaN

[4078318 rows x 3 columns]

In [68]:
# Sort the selected columns 'FlightDate', 'Airline', 'ArrDelay' by 'ArrDelay' column in descending order,
# and reset the index
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False).reset_index(drop=True)

        FlightDate                 Airline  ArrDelay
0       2022-05-23       Republic Airlines    7232.0
1       2022-06-18               Envoy Air    5324.0
2       2022-05-16       Republic Airlines    4318.0
3       2022-06-05  American Airlines Inc.    2977.0
4       2022-03-26  American Airlines Inc.    2934.0
...            ...                     ...       ...
4078313 2022-03-31       Republic Airlines       NaN
4078314 2022-03-31       Republic Airlines       NaN
4078315 2022-03-17       Republic Airlines       NaN
4078316 2022-03-25       Republic Airlines       NaN
4078317 2022-03-07       Republic Airlines       NaN

[4078318 rows x 3 columns]

In [69]:
# Sort the selected columns 'FlightDate', 'Airline', 'ArrDelay' by index in ascending order
df[['FlightDate', 'Airline', 'ArrDelay']].sort_index(ascending=True)

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
0      2022-05-03                                Comair Inc.       1.0
0      2022-01-06                       Delta Air Lines Inc.       NaN
0      2022-07-19                                Comair Inc.     -29.0
0      2022-03-08                       Delta Air Lines Inc.     -14.0
...           ...                                        ...       ...
618785 2022-07-01                          Republic Airlines      18.0
618786 2022-07-01                          Republic Airlines     -25.0
618787 2022-07-01                          Republic Airlines      20.0
618788 2022-07-01                          Republic Airlines      43.0
618789 2022-07-01                          Republic Airlines     183.0

[4078318 rows x 3 columns]

In [70]:
# Sort the selected columns 'FlightDate', 'Airline', 'ArrDelay' by index in descending order
df[['FlightDate', 'Airline', 'ArrDelay']].sort_index(ascending=False)

       FlightDate                                    Airline  ArrDelay
618789 2022-07-01                          Republic Airlines     183.0
618788 2022-07-01                          Republic Airlines      43.0
618787 2022-07-01                          Republic Airlines      20.0
618786 2022-07-01                          Republic Airlines     -25.0
618785 2022-07-01                          Republic Airlines      18.0
...           ...                                        ...       ...
0      2022-03-08                       Delta Air Lines Inc.     -14.0
0      2022-07-19                                Comair Inc.     -29.0
0      2022-01-06                       Delta Air Lines Inc.       NaN
0      2022-05-03                                Comair Inc.       1.0
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0

[4078318 rows x 3 columns]

# Handling Missing Data

In [71]:
# Count the number of missing values in each column 'FlightDate', 'Airline', 'ArrDelay'
df[['FlightDate', 'Airline', 'ArrDelay']].isna().sum()

FlightDate         0
Airline            0
ArrDelay      133402
dtype: int64

In [72]:
# Drop rows with missing values in the 'ArrDelay' column
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset=['ArrDelay'])

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -1.0
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -3.0
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -18.0
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.       6.0
...           ...                                        ...       ...
590532 2022-03-31                          Republic Airlines     207.0
590533 2022-03-31                          Republic Airlines     201.0
590534 2022-03-31                          Republic Airlines     180.0
590536 2022-03-19                          Republic Airlines     135.0
590539 2022-03-08                          Republic Airlines     381.0

[3944916 rows x 3 columns]

In [73]:
# Count the number of missing values in each column after dropping rows with missing values in the 'ArrDelay' column
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset=['ArrDelay']).isna().sum()

FlightDate    0
Airline       0
ArrDelay      0
dtype: int64

In [74]:
# Fill missing values in the 'ArrDelay' column with 0
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(0)

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -1.0
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -3.0
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -18.0
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.       6.0
...           ...                                        ...       ...
590537 2022-03-31                          Republic Airlines       0.0
590538 2022-03-17                          Republic Airlines       0.0
590539 2022-03-08                          Republic Airlines     381.0
590540 2022-03-25                          Republic Airlines       0.0
590541 2022-03-07                          Republic Airlines       0.0

[4078318 rows x 3 columns]

In [75]:
# Count the number of missing values in each column after filling missing values in the 'ArrDelay' column with 0
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(0).isna().sum()

FlightDate    0
Airline       0
ArrDelay      0
dtype: int64

In [76]:
# Fill missing values in the 'ArrDelay' column with the mean of the column
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(df['ArrDelay'].mean())

       FlightDate                                    Airline    ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.  -17.000000
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.   -1.000000
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.   -3.000000
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.  -18.000000
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    6.000000
...           ...                                        ...         ...
590537 2022-03-31                          Republic Airlines    7.528486
590538 2022-03-17                          Republic Airlines    7.528486
590539 2022-03-08                          Republic Airlines  381.000000
590540 2022-03-25                          Republic Airlines    7.528486
590541 2022-03-07                          Republic Airlines    7.528486

[4078318 rows x 3 columns]

In [77]:
# Count the number of missing values in each column after filling missing values in the 'ArrDelay' column with the mean
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(df['ArrDelay'].mean()).isna().sum()

FlightDate    0
Airline       0
ArrDelay      0
dtype: int64

# Combining Data

In [78]:
# Create DataFrame df1 with rows where Airline is "Southwest Airlines Co."
df1 = df.query('Airline == "Southwest Airlines Co."').copy()

# Create DataFrame df2 with rows where Airline is "Delta Air Lines Inc."
df2 = df.query('Airline == "Delta Air Lines Inc."').copy()

# Stack df1 and df2 vertically
df_stack = pd.concat([df1, df2])

In [79]:
# Reset index for df1 and df2
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

# Concatenate df1 and df2 horizontally
df_side = pd.concat([df1, df2], axis=1)

In [80]:
# Display shapes of original DataFrame df, df2, stacked DataFrame df_stack, and side-by-side DataFrame df_side
df.shape, df2.shape, df_stack.shape , df_side.shape

((4078318, 63), (512114, 63), (1244039, 63), (731925, 126))

# Merge Data

## df.merge()

In [81]:
# Group by 'Airline' and 'FlightDate' and calculate the mean of 'DepDelay'
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()

# Group by 'Airline' and 'FlightDate' and calculate the mean of 'ArrDelay'
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [82]:

# Merge df1 and df2 using the default inner join
df_inner = df1.merge(df2)

# Merge df1 and df2 using inner join explicitly
df_inner_explicit = df1.merge(df2, how='inner')

# Merge df1 and df2 using left join
df_left = df1.merge(df2, how='left')

# Merge df1 and df2 using right join
df_right = df1.merge(df2, how='right')

# Merge df1 and df2 using outer join
df_outer = df1.merge(df2, how='outer')

# pd.merge()

In [83]:
# Group by 'Airline' and 'FlightDate' and calculate the mean of 'DepDelay'
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()

# Group by 'Airline' and 'FlightDate' and calculate the mean of 'ArrDelay'
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [84]:
# Merge df1 and df2 using the default inner join
pd.merge(df1, df2)

# Merge df1 and df2 on specified columns
pd.merge(df1, df2, on=['Airline', 'FlightDate'])

# Merge df1 and df2 on 'Airline' column with suffixes for disambiguation
pd.merge(df1, df2, on='Airline', suffixes=('_dep', '_arr'))

# Merge df1 and df2 using left_on and right_on parameters
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857

# Done!!!